name: droidenv2
channels:
  - rusty1s
  - pytorch
  - open3d-admin
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pytorch-scatter
  - torchaudio=0.9.1=py38
  - torchvision=0.10.1=py38_cu111
  - open3d
  - pytorch=1.9.1=py3.8_cuda11.1_cudnn8.0.5_0
  - cudatoolkit=11.1
  - tensorboard
  - scipy
  - opencv
  - tqdm
  - suitesparse
  - matplotlib
  - pyyaml
